trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  jobs:
  - job: primeiroJob
    steps:
    - bash: echo Primeiro Job do Build
    - bash: echo $(pipelineLevelVariable)
      displayName: "echo pipelineLevelVariable"
    - bash: echo $(Build.BuildNumber)
      displayName: "echo BuildNumber"
  - job: segundoJob
    steps:
    - bash: echo Segundo Job do Build
    - bash: echo $(Build.BuildId)
      displayName: "echo buildId"
    - bash: echo $(Build.SourceBranchName)
      displayName: "echo SourceBranch"

- stage: deployDSV
  dependsOn: Build
  jobs:
  - job: deployDSVjob
    steps:
    - bash: echo Deploy em DSV
    - bash: echo $(environment) deploy job
      displayName: "echo environmentVar"
    - bash: echo $(Build.SourceDirectory)
      displayName: "echo SourceDIrectory"
    - bash: echo $(System.DefaultWorkingDirectory)
      displayName: "echo workingDirectory"
  - deployment: DSVdeploy
    environment: DSV

- stage: deployHMG
  dependsOn: Build
  jobs:
  - job: deployHMGjob
    steps:
    - bash: echo Deploy em HMG
    - bash: java -version
      displayName: "Vers達o Java"
    - bash: mvn -version
      displayName: "Vers達o Maven"
    - bash: node --version
      displayName: "Vers達o Node"
    - bash: python --version
      displayName: "Vers達o Python"
  - deployment: HMGdeploy
    environment: HMG

- stage: deployPRD
  dependsOn: deployHMG
  jobs:
  - job: deployPRDjob
    steps:
    - bash: echo Deploy em PRD
    - bash: ls -R $(System.DefaultWorkingDirectory)
      displayName: "echo WorkingDirectory"
    - bash: echo $(Build.ArtifactStagingDirectory)
      displayName: "echo artifactStagingDirectory"
    - bash: ls -R $(Build.ArtifactStagingDirectory)
      displayName: "list stagingDirectory"
  - deployment: PRDdeploy
    environment: PRD
    